services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile_cliente
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile_server
    ports:
      - "3001:3001"
    env_file: ./.env
    environment:
      NODE_ENV: development
      DB_URL: ${DB_URL}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
